create TABLE DBO.ETL_METADATA (
	ETL_METADATA_ID NUMBER(38,0) autoincrement,
	NOTIFICATION_INTEGRATION VARCHAR(100),
	NOTIFICATION_EMAIL VARCHAR(5000),
	NOTIFICATION_SUBJECT VARCHAR(500),
	CREATED_DATE TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(255) DEFAULT CURRENT_USER(),
	UPDATED_DATE TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_BY VARCHAR(255) DEFAULT CURRENT_USER()
);
